variables:
  NUGET_PATH: 'C:\NuGet\nuget.exe'
  MSBUILD_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\msbuild.exe'

stages:
  - build
build_job:
  stage: build
  tags:
    - netframework
  #only:
  #  - tags # the build process will only be started by git tag commits
  script:
    #- '& "$env:NUGET_PATH" restore' # restore Nuget dependencies
    - '& cd ./DOJ.Core.Framework'
    - '& "$env:MSBUILD_PATH" /p:Configuration=Release' # build the project
  artifacts:
    expire_in: 1 week # save gitlab server space, we copy the files we need to deploy folder later on
    paths:
      - 'DOJ.Core.Framework\DOJ.Core.Framework.Shared\bin\Release\**'
      - 'DOJ.Core.Framework\DOJ.Core.Framework.Server\bin\Release\**'
      - 'DOJ.Core.Framework\DOJ.Core.Framework.Client\bin\Release\**'